<a href="https://colab.research.google.com/github/Pritipirojia/AI_Engineering_Tutorial_Notes/blob/main/pandas_series_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pandas

Pandas is a powerful library used for data manipulation and analysis. It helps us to work with data in Tabular format, just like how we deal with data and spreadsheet in excel or data.

Pandas provides functionalities and attributes to clean, organize and analyze large amounts of data

1. Easy to use---> Works like Excel inside python
2. Fast---> Handles large data faster than manual methods
3. Clean data---> helps clean, filter and transform messy data
4. Integrates well---> Matplotlib, Seaborn
5. Ideal for data science, ML and AI

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import numpy as np
import pandas as pd

Pandas series is a column of data in a table like in excel or google sheets with labels called as indexes attached to each value

In [ ]:
pd.Series(data=[40,50,60],index=['Bread', 'Milk', 'Butter'], name='Price of grocery items')

Bread     40
Milk      50
Butter    60
Name: Price of grocery items, dtype: int64

Whenever you create a series, data type is always going to be decided on the basis of the values itself that are there in the series

Series is a 1D array that can hold any type of data like integers, float, string (objects), boolean, mixed data type.

## Creating a series in multiple ways
1. List
2. Numpy array
3. Dictionary
4. custom index
5. scalar value

In [ ]:
## series from list
country=['India', 'china', 'USA', 'Pakistan']
pd.Series(country)

0       India
1       china
2         USA
3    Pakistan
dtype: object

In [ ]:
batsman_runs=[48,64,73,98,65,90]
pd.Series(batsman_runs, dtype='int32')

0    48
1    64
2    73
3    98
4    65
5    90
dtype: int32

In [ ]:
subject_names=['Maths', 'Physics', 'Chemistry', 'English']
subject_marks=[48,92,67,98]

pd.Series(data=subject_marks, index=subject_names, name='Subject Marks data', dtype='int32')

Maths        48
Physics      92
Chemistry    67
English      98
Name: Subject Marks data, dtype: int32

In [ ]:
### Creating an series using a numpy array
values=np.arange(10,21)
pd.Series(values)

0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
dtype: int64